### ISSUE TITLE
Unable to find "doColorRamp" function

### ISSUE THREAD

**Issue by BardoBravo** [hadley/scales#80] opened 2016-10-06 06:59 UTC
Hello,
When I try to execute function addPolygons() from package leaflet, I receive the following error:
Error in f(x) : could not find function "doColorRamp"

Such issue only happens if I use the color parameter with a collorPalette:

leaflet::leaflet(nhmap) %>% leaflet::addProviderTiles("CartoDB.Positron") %>% leaflet::addPolygons(stroke=FALSE, smoothFactor = 0.2, fillOpacity = .8, popup = nhpopup, fillColor = ~clintonPalette(nhmap@data$ClintonPct))
I have already used require() and library() functions, but even so the issue persists.

Any help would be great.
Regards,
Cláudio

**Comment by karawoo** [comment] 2017-06-14 16:50
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by karawoo** [comment] 2017-07-27 16:32
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by karawoo** 2017-07-27 16:32 UTC
Labels: reprex
